### ISSUE TITLE
not working after OPGG update

### ISSUE THREAD

**Issue by BVLLISTA** [MidKnightXI/opgg-ads-remover#16]
not working after the latest opgg update (3-4 days ago).

**Comment by huntervcx** [comment]
Hi There ! 

Could you provide more information please ? as the template indicate : 

Describe the bug
A clear and concise description of what the bug is.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.

Desktop (please complete the following information):

OS: [e.g. Windows, Ubuntu]
Browser [e.g. chrome, safari]
Version [e.g. 22]
Additional context
Add any other context about the problem here.

**Comment by MidKnightXI** [comment]
Hello,

Thank you for reporting that problem, but please do as said above, fill the template given as example when opening an issue to help us fixing it.

And avoid in the future to just add in description *"it's not working, please fix"* because it won't help us at all.

**Comment by BVLLISTA** [comment]
Describe the bug
The script doesn't work anymore after the latest OPGG update which released 3-4 days ago.

To Reproduce
Start OP.GG Desktop App, apply patch with [opgg-ads-remover]

Desktop
OS: Windows 11

Screenshots
![Screenshot 2023-02-13 010931](https://user-images.githubusercontent.com/107594745/218383891-a4579b75-0613-4dc7-b9ab-ccfa60e7e62a.png)

**Comment by MidKnightXI** [comment]
Thank you for reacting that fast, I'm going to start working on it asap and keep you updated when it'll be fixed.

**Comment by BVLLISTA** [comment]
My thanks, sorry for opening an issue the lazy way!

**Comment by MidKnightXI** [comment]
The directory that was specified in the code where the ads were(assets/react) got removed and got replaced by a main directory containing main.js and preload.js.

Im still looking into it to find where the ad links are located with that new update but I guess we will have to work with that assets/main directory.

**Comment by MidKnightXI** [comment]
The directory that was specified in the code where the ads were(`assets/react`) got removed and got replaced by a `main` directory containing `main.js` and `preload.js`.

Im still looking into it to find where the ad links are located with that new update but I guess we will have to work with that `assets/main` directory.

<img width="281" alt="image" src="https://user-images.githubusercontent.com/35759490/218432723-9fb7de70-4dee-4d55-88d0-5d1a508ce0a3.png">

**Comment by MidKnightXI** [comment]
I think I identified where the ads are loaded, I'm going to start doing some tests to see if I can remove them tomorow

**Comment by noahye1997** [comment]
2.0.6 doesn't work for USA ads
![image](https://user-images.githubusercontent.com/38360170/220203827-d4fe5059-2231-4625-baa0-e8b360b75b0e.png)

**Comment by MidKnightXI** [comment]
2.0.6 only works for opgg on macOS atm because they haven't gotten the opgg update yet.

Also deleting these ads is harder than what I expected.

**Comment by MidKnightXI** [comment]
2.0.6 only works for opgg on macOS atm because they haven't gotten the opgg update yet.

**Comment by MidKnightXI** [comment]
Also I think I'll wait for the update to roll out on macOS to test it better because rn I've to build everything on an arm window virtual machine and it's a pain.

I'll continue to search for a fix but it will be longer than what I expected

**Comment by TogoFire** [comment]
@MidKnightXI How to revert. My opgg doesn't work anymore. Doesn't load any page after patch.

**Comment by MidKnightXI** [comment]
> @MidKnightXI How to revert? My opgg doesn't work anymore. Doesn't load any page after patch.

Can you send screenshots?
You shouldn't have any problems as it's not changing any files since the new update.
Either way to revert that, you just have to reinstall opgg.

**Comment by BVLLISTA** [comment]
OP.GG app received another update on Windows, V1.1.15

**Comment by NaabKing** [comment]
> OP.GG app received another update on Windows, V1.1.15

Yes, and the new update is the worst one yet, ads are part of the app now, not seperate, the size is bigger and can't be resized anymore, i hate it. Hopefully this can be patched somehow.

**Comment by MidKnightXI** [comment]
Working on it, but I feel like it's going to be complicated to patch.

If anyone want to test to find a way to fix it:

- Download OPGG
- Open where it's located `C:\Users\$USER\AppData\Local\Programs\OP.GG\ressources`
- Copy `app.asar` and `app.asar.unpacked` to the place you want
- Install [asar tool](https://github.com/electron/asar) from electron team with npm in the folder you put the archive
- Open `package.json` and add
```json
"script": {
    "asar": "asar e app.asar archive"
}
```
- Run `yarn asar` and go to `assets\main\main.js`
- Find a fix ✨

**Comment by MidKnightXI** [comment]
Hello everyone, I asked [Shyim](https://github.com/shyim/op-gg-remove-ads/issues/10) for some help on that issue and he found a fix 👑

Go star his project to thanks him, I'll drop a new release soon after finishing some testing on my side to check if everything is working as intended
