### ISSUE TITLE
Overlay Not Working When Patch Applied

### ISSUE THREAD

**Issue by Swishnu** [MidKnightXI/opgg-ads-remover#18]
**Describe the bug**
Once patch has been applied the overlay does not function at all

**To Reproduce**
1. Activate Path
2. Use OP.GG as Normal
3. Try To Use/Activate Overlay nothing appears

**Expected behavior**
the overlay with the levels and CS/GOLD should show up

**Additional context**
The Issue was fixed if I did a fresh install of OP.GG without the patch applied

**Comment by MidKnightXI** [comment]
Thank you for reporting the issue,

I'll look into that in two weeks: exam period 😞

**Comment by MidKnightXI** [comment]
Can you tell me if the new release is fixing your problem?

**Comment by Swishnu** [comment]
No the issue is still persisting

**Comment by MidKnightXI** [comment]
https://github.com/MidKnightXI/opgg-ads-remover/releases/tag/v2.3.0

Ads are still showing up but some tracking services are removed from the app.

I'll see how to improve it with time
