### ISSUE TITLE
Ad Blocker Not Working in OP.GG Version 1.1.21

### ISSUE THREAD

**Issue by BVLLISTA** [MidKnightXI/opgg-ads-remover#19]
Describe the bug
The ad blocking feature is not working in OP.GG app version 1.1.21 

To Reproduce
Install the latest version of OP.GG
Run OP.GG Patcher
Open OP.GG after successful patch

Expected behavior
The ads will be removed from the app after successful patch, until a new OP.GG update releases.

Screenshots
![image](https://user-images.githubusercontent.com/107594745/233688429-e312a93f-012c-4498-9900-8ad063b17c93.png)

OS: Windows
Version: 11
OP.GG App Version: V.1.1.21

**Comment by shyim** [comment]
Adopt this replace and it works again :) 
https://github.com/shyim/op-gg-remove-ads/commit/dc1a8868260ad137df6a616e391d2a3f2999118e#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R54

**Comment by MidKnightXI** [comment]
> Adopt this replace and it works again :) 
> https://github.com/shyim/op-gg-remove-ads/commit/dc1a8868260ad137df6a616e391d2a3f2999118e#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R54

Thank you a lot @shyim !

**Comment by MidKnightXI** [comment]
Actually even without adding the `app.labs.sydney` it's working for me on my side
