### ISSUE TITLE
Ads still popup

### ISSUE THREAD

**Issue by iamSky11425** [MidKnightXI/opgg-ads-remover#24]
**Describe the bug**
After patching with version 2.1.2 ads still popup on the right side of the op.gg application.

**To Reproduce**
1. Go to 'patch installer and install'
2. Click on 'op.gg application'
3. Scroll down to 'nowhere, the ads should popup on the first page the application opens'

**Expected behavior**
Patch patches

**Screenshots**
![image](https://github.com/MidKnightXI/opgg-ads-remover/assets/29107416/32d6d20a-9ba5-47a3-b58a-175c45956c3d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 2.1.2

**Additional context**
the install button on the main page installs 2.1.1 but this was tested with 2.1.2 and 2.1.1

**Comment by MidKnightXI** [comment]
> the install button on the main page installs 2.1.1 but this was tested with 2.1.2 and 2.1.1
Just patched it, now you should be able to install the good version.

Also I'll look into that next week as I'm coming back to my home country and will have access to a Windows machine

**Comment by MidKnightXI** [comment]
After checking myself, the ads are not popping up on my side:

### Before patch

<img width="1728" alt="image" src="https://github.com/MidKnightXI/opgg-ads-remover/assets/35759490/53b51bf4-6a0d-4176-b946-2df194845651">

### After patch

<img width="1728" alt="image" src="https://github.com/MidKnightXI/opgg-ads-remover/assets/35759490/9d8024b9-019f-417b-9b41-32c6b9ef898f">

So I don't really see what is your problem

**Comment by iamSky11425** [comment]
I just did a fresh install of both the op.gg application and the patcher and it worked :)
