### ISSUE TITLE
Typo: Readme's line 15

### ISSUE THREAD

**Issue by afar-cmyk** [MidKnightXI/opgg-ads-remover#3]
Remove one of the `clone` from line 15, and add a dot at the end of the paragraph.

Master:
``` git clone clone https://github.com/MidKnightXI/opgg-ads-remover.git```

Fixed:
`git clone https://github.com/MidKnightXI/opgg-ads-remover.git`

**Comment by MidKnightXI** [comment]
oups mb I'll fix it tonight thanks for mentioning it

**Comment by MidKnightXI** [comment]
fixed
