### ISSUE TITLE
OPGG PATCHER 2.3.0 cannot work in OPGG version 1.1.28 or latest ver.

### ISSUE THREAD

**Issue by frankieyim** [MidKnightXI/opgg-ads-remover#31]
Hi  I wanted to report an issue with the patcher version 2.3.0. It doesn't seem to work properly with OPGG version 1.1.28 or the latest version. After applying the patch, advertisements still appear in the OPGG software. Could you please review and update the patch to resolve this problem? Thanks a bunch!

**Comment by MidKnightXI** [comment]
Hello, as said in #30 the 2.3 is here if you want to have access to the live features either way if you don't want ads to show up, use 2.2.0.

If ads are still showing up with 2.2.0 please comment on this issue and I will rename it.

Also by using 2.3.0 ads are still showing up but the patcher is deleting some trackers used in background
